### ISSUE TITLE
Enable CLA or DCO bot

### ISSUE THREAD

**Issue by jessesuen** [oss-workshop/grace-hopper-example#10]
CLA Bot: https://github.com/apps/cla-bot

DCO Bot: https://github.com/probot/dco

**Comment by jessesuen** [comment]
I think DCO is easier to setup since it doesn't require signing of a legal document, and more appropriate for this example.

**Comment by jessesuen** [comment]
Resources

- https://opensource.com/article/18/3/cla-vs-dco-whats-difference
- https://helm.sh/blog/helm-dco/

**Comment by khhirani** [comment]
Enabled DCO: https://github.com/organizations/oss-workshop/settings/installations/11858404
