### ISSUE TITLE
Calculate square of given number

### ISSUE THREAD

**Issue by oss-contributor** [oss-workshop/grace-hopper-example#29]
# Summary

I would like the ability to calculate the square of a given number.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by khhirani** [comment]
Hi @oss-contributor, this feature doesn't fit in with our project. Thanks for the suggestion though.

Closing this issue.
